apiVersion: v1
kind: Service
metadata:
  name: hworld
  labels:
    app: hworld
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: hworld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hworldv1
  labels:
    app: hworld
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hworld
      version: 1.0.0
  template:
    metadata:
      labels:
        app: hworld
        version: 1.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9101"
    spec:
      containers:
      - name: hworld
        image: hgautam007/harish:1.0.2
        ports:
        - name: http
          containerPort: 8080

