apiVersion: apps/v1
kind: Deployment
metadata:
  name: hworld-appversion2
  labels:
    app: hworld
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hworld
      version: 2.2.2
  template:
    metadata:
      labels:
        app: hworld
        version: 2.2.2
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9100"         
    spec:
      containers:
      - name: hworld
        image: hgautam007/harish:2.2.2
        ports:
        - name: http
          containerPort: 8080
        