apiVersion: v1
kind: Service
metadata:
  name: hworld
  labels:
    app: hworld
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: hworld
    version: 1.1.1
          
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hworld-appversion1
  labels:
    app: hworld
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hworld
      version: 1.1.1
  template:
    metadata:
      labels:
        app: hworld
        version: 1.1.1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9100"         
    spec:
      containers:
      - name: hworld
        image: hgautam007/harish:1.1.1
        ports:
        - name: http
          containerPort: 8080


