apiVersion: apps/v1
kind: Deployment
metadata:
  name: hworld
  labels:
    app: hworld
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: hworld
  template:
    metadata:
      labels:
        app: hworld
        version: 1.1.1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9100"        
    spec:
      containers:
      - name: hworld
        image: hgautam007/harish:1.1.1
        ports:
        - name: http
          containerPort: 8080
       
        
---
apiVersion: v1
kind: Service
metadata:
  name: hworld
  labels:
    app: hworld
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: hworld


